import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/Providers";

const opensans = Open_Sans({ 
  subsets: ["latin"],
  weight: ["300", "400", "500", "600",  "700", "800"],
  variable: "--font-opensans"
});

export const metadata: Metadata = {
  title: "Fay's Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={opensans.className}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
